name: AWS using OIDC

on:
  workflow_dispatch:

jobs:
  test:
    name: Login to AWS using OIDC
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: ls -la
